### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by cibernox** [godsent/rpg-maker-slides#1]
I'm creating a simple RPG where at some point I want to display some pictures as slides (with the ability going back and forward).

Could you add some readme file with instructions to install and use this plugin.

I'm using RPG MV in case it matters.

Thanks.

**Comment by godsent** [comment]
Hello. This script was written for RPG Maker VX ACE (uses ruby) so you can't use it for RPG Maker MV (uses JavaScript).
